name: iotdevice-device-ui
base: core20
version: '0.1' 
summary: Device UI for Demo Purposes
description: |
  This is the main UI application for Demo purposes

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64


apps:
  ui-app:
    command: bin/npm run dev
  ui-service:
    command: bin/http-server $SNAP/static -p 8000 --cors
    daemon: simple
    plugs:
      - network
      - network-bind
  backend:
    command: launch.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control

parts:
  ui:
    plugin: npm
    npm-node-version: 16.15.0
    source: app
    build-packages:
      - build-essential
    override-build: |
      # install node dependencies
      snapcraftctl build
      # Install and Build Project
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/static/
      cp -r dist/* $SNAPCRAFT_PART_INSTALL/static/
  
  http-server:
    plugin: npm
    npm-node-version: 16.15.0
    source: https://github.com/http-party/http-server.git
    source-tag: v14.1.0

  backend:
    plugin: python
    source: backend
    requirements: 
      - requirements.txt
    
  python-source:
    source: backend
    plugin: dump

  launcher:
    source: bin
    plugin: dump