name: iotdevice-device-ui
base: core22
version: '22'
summary: Device UI for Demo Purposes
description: |
  This is the main UI application for Demo purposes

grade: stable
confinement: strict

apps:
  ui-app:
    command: usr/bin/npm run dev
  ui-service:
    command: bin/serve -l 4000 -s $SNAP/static
    daemon: simple
    plugs:
      - network
      - network-bind
  backend:
    command: launch.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control

parts:
  npm-deps:
    plugin: nil
    stage-snaps:
      - nodejs-binaries

  ui:
    plugin: npm
    after: [npm-deps]
    source: app
    build-packages:
      - build-essential
    override-build: |
      # install node dependencies
      craftctl default
      # Install and Build Project
      npm install
      npm run build
      mkdir -p "${CRAFT_PART_INSTALL}"/static/
      cp -r dist/* "${CRAFT_PART_INSTALL}"/static/

  http-server:
    plugin: npm
    after: [npm-deps]
    source: https://github.com/http-party/http-server.git
    source-tag: v14.1.0

  pushstate-server:
    plugin: npm
    after: [npm-deps]
    source: https://github.com/scottcorgan/pushstate-server.git
    source-tag: 3.1.0

  serve:
    plugin: npm
    after: [npm-deps]
    source: https://github.com/vercel/serve.git
    source-tag: 14.2.1
    override-build: |
      npm install pnpm
      craftctl default

  backend:
    plugin: python
    source: backend
    python-requirements:
      - requirements.txt

  python-source:
    source: backend
    plugin: dump

  launcher:
    source: bin
    plugin: dump
